
openapi: "3.0.1"
info:
  title: IOT-Inspector-Server
  version: 1.0.0
paths:
  /:
    get:
      operationId: home
      summary: root debug page
      responses:
        '200':
          description: |-
            200 response
          content:
            text/plain:
              schema:
                type: string

  /submit_data/{user_key}:
    post:
      operationId: submitData
      summary: Upload data to the backend.
      parameters:
        - name: user_key
          in: path
          required: true
          description: the current user's key
          schema:
            type: string
      requestBody:
        content: 
          application/json:
            schema:
              $ref: '#/components/schemas/upload'
      responses:
        '200':
          description: |-
            200 response
          content:
            text/plain:
              schema:
                type: string
        '400':
          description: Bad request

  /generate_user_key:
    get:
      operationId: generateUserKey
      summary: Generate a new user key.
      responses:
        '200':
          description: The generated key.
          content:
            text/html:
              examples:
                text/html: 
                  value: '<html><head></head><body>123abc456def7890----------------</body></html>'

  /submit_utc_offset/{user_key}/{offset_seconds}:
    get:
      operationId: submitUTCOffset
      summary: Send client's timezone to the server.
      parameters:
        - name: user_key
          in: path
          required: true
          description: the current user's key
          schema:
            type: string
        - name: offset_seconds
          in: path
          required: true
          description: The user's utc offset in seconds.
          schema:
           type: integer
      responses:
        '200':
          description: All responses are 200
          content:
            text/html:
              examples:
                success: 
                  value: 'SUCCESS'
                failure: 
                  value: 'ERROR: Invalid offset_seconds.'

components:
  schemas:
    upload:
      type: object
      properties:
        client_status_text:
          type: string
        dns_dict:
          type: string
        syn_scan_dict:
          type: string
        flow_dict:
          type: string
        device_dict:
          type: string
        ua_dict:
          type: string
        dhcp_dict:
          type: string
        resolver_dict:
          type: string
        client_version:
          type: string
        tls_dict_list:
          type: string
        netdisco_dict:
          type: string
        duration:
          type: string
        client_ts:
          type: string
