
openapi: "3.0.1"
info:
  title: IOT-Inspector-Server
  version: 1.0.0
paths:
  /:
    get:
      operationId: home
      summary: displays consent page
      responses:
        '200':
          description: |-
            200 response
          content:
            text/plain:
              schema:
                type: string

  /submit_data/{user_key}:
    post:
      operationId: submitData
      summary: Upload data to the backend.
      parameters:
        - name: user_key
          in: path
          required: true
          description: the current user's key
          schema:
            type: string
      requestBody:
        content: 
          application/json:
            schema:
              $ref: '#/components/schemas/upload'
      responses:
        '200':
          description: |-
            200 response
          content:
            text/plain:
              schema:
                type: string
        '400':
          description: Bad request

  /submit_fingerprint/{user_key}:
    post:
      operationId: submitFingerprint
      summary: Upload device fingerprints to the backend.
      parameters:
        - name: user_key
          in: path
          required: true
          description: the current user's key
          schema:
            type: string
      requestBody:
        content: 
          application/json:
            schema:
              $ref: '#/components/schemas/fingerprint'
      responses:
        '200':
          description: |-
            200 response
          content:
            text/plain:
              schema:
                type: string
        '400':
          description: Bad request

  /generate_user_key:
    get:
      operationId: generateUserKey
      summary: Generate a new user key.
      responses:
        '200':
          description: The generated key.
          content:
            text/html:
              examples:
                text/html: 
                  value: '<html><head></head><body>123abc456def7890----------------</body></html>'

  /heartbeat:
    get:
      operationId: heartBeat
      summary: send a heartbeat to the server to let it know we are connected.
      responses:
        '200':
          description: Acknowledgement.
          content:
            text/plain:
              schema:
                type: string

  /submit_utc_offset/{user_key}/{offset_seconds}:
    get:
      operationId: submitUTCOffset
      summary: Send client's timezone to the server.
      parameters:
        - name: user_key
          in: path
          required: true
          description: the current user's key
          schema:
            type: string
        - name: offset_seconds
          in: path
          required: true
          description: The user's utc offset in seconds.
          schema:
           type: integer
      responses:
        '200':
          description: All responses are 200
          content:
            text/html:
              examples:
                success: 
                  value: 'SUCCESS'
                failure: 
                  value: 'ERROR: Invalid offset_seconds.'

  # NB (nphair): Not sure what this end point is for. 
  # It redirects to the dashboard.
  /user/{user_key}:
    get:
      operationId: userUserKey  
      summary: na
      parameters:
        - name: user_key
          in: path
          required: true
          description: the current user's key
          schema:
            type: string
      responses:
        '302':
          description: Redirects to dashboard
          headers:
            Set-Cookie:
              description: Session cookie
              schema:
                type: string
                example: user_key=123abc456def7890; Path=/
            # https://github.com/OAI/OpenAPI-Specification/issues/1237#issuecomment-423955715
            "\0Set-Cookie":
              description: Session cookie
              schema:
                type: string
                example: persistent_mode=yes; Path=

components:
  schemas:
    upload:
      type: object
      properties:
        client_status_text:
          type: string
        dns_dict:
          type: string
        syn_scan_dict:
          type: string
        flow_dict:
          type: string
        device_dict:
          type: string
        ua_dict:
          type: string
        dhcp_dict:
          type: string
        resolver_dict:
          type: string
        client_version:
          type: string
        tls_dict_list:
          type: string
        netdisco_dict:
          type: string
        duration:
          type: string
        client_ts:
          type: string
    fingerprint:
      type: object
      properties:
        name:
          type: string
        fingerprint:
          type: array
          items:
            type: number
